### ISSUE TITLE
Please support ColorMode::Rgb (no alpha channel)

### ISSUE THREAD

**Issue by walles** [blaind/webp-animation#11]
Hi!

My input is in RGB format, with no alpha channel.

To encode this I'd like to specify `ColorMode::Rgb`, but the currently supported color modes have alpha channels:
https://github.com/blaind/webp-animation/blob/abe766438fc0418d88d2664fa510a328b4922277/src/lib.rs#L40-L48

Could you please add an RGB `ColorMode`?

**Comment by blaind** [comment]
This is now released to crates.io in version 0.8
