### ISSUE TITLE
How to encode a looping animation?

### ISSUE THREAD

**Issue by walles** [blaind/webp-animation#13]
I want to make my animation run in a loop.

But searching for "loop" in here doesn't give me any hints on how to do that.

In the C library [looping is part of the encoder options](https://github.com/webmproject/libwebp/blob/08d60d60066eb30ab8e0e3ccfa0cd0b68f8cccc6/src/webp/mux.h#L423-L442).

**Comment by blaind** [comment]
The library does looping by default.

However, there was another configuration option which would limit the loop count. Created a pull request #15

**Comment by walles** [comment]
When I tried it I got a not-looping animation by default and I was unable to figure out how to fix that:
https://github.com/walles/loadviz/blob/9e82365e9eef42a93d14b0cb0a88b5c427d082f8/libloadviz/src/bin/screenshot.rs

The code ^ has moved along since then, but if you do `cargo run --bin=screenshot` at the above SHA you should get a 10s not-looping screenshot in `screenshot.webp`.

I used Firefox to look at the generated `screenshot.webp` image.

**Comment by blaind** [comment]
Part of the code in the above link:
```
  let frames_per_second = 10;
  let seconds = 10;

  for i in 0..(frames_per_second * seconds - 1) {
      let dt_seconds = i as f64 / frames_per_second as f64;
      let dt_milliseconds = (dt_seconds * 1000.0) as i32;

      println!("frame {}", dt_milliseconds);
  }

  let final_milliseconds = frames_per_second * seconds * 1000;
  println!("final ts {}", final_milliseconds);
```

outputs
```
...
frame 9500
frame 9600
frame 9700
frame 9800
final ts 100000
```
the final timestamp (for `finalize`) determines the duration of the last frame, hence last frame being shown for 100000-9800 ms.

I added a brief note to the function documentation. Would this help?

**Comment by walles** [comment]
My issue is that when I ran my code, the resulting webp only played once and then stopped when I opened it in Firefox.

Here's the not-looping screenshot generated by the above code:
![screenshot](https://github.com/blaind/webp-animation/assets/158201/0b250be9-b3b4-4f98-85e5-b15205957de4)

It *is* a webp, but I'm naming it `.gif` as a workaround for <https://github.com/orgs/community/discussions/5470>.

**Comment by blaind** [comment]
Did you wait to see if it looped over after 90.2 seconds (100000-9800/1000), caused by the last timestamp (100_000ms)? Would it be possible to upload the raw procuded webp somewhere?

**Comment by walles** [comment]
> frame 9800
> final ts 100000

I missed that there was a 10x difference here, sorry.

What you're saying is that this line is wrong, and I think you're right:
https://github.com/walles/loadviz/blob/9e82365e9eef42a93d14b0cb0a88b5c427d082f8/libloadviz/src/bin/screenshot.rs#L66

Not sure what could be done on your end that would have helped me spot / avoid this.

I'll just chalk it down to my fault and close this ticket.

Thanks for looking into it @blaind!
