### ISSUE TITLE
Frame Rate

### ISSUE THREAD

**Issue by mehmetakify** [blaind/webp-animation#7]
After decode an animated webp file I need to encode it to gif with another libray. It works but I dont know the frame rate and new gif has different speed.

Is there a way to get frame rates? If there is no such a feature it would be very useful.

Thank you for this amazing library.

**Comment by blaind** [comment]
In WebP, each frame may have separate timestamp - there's no concept of a fixed framerate.

You can use `frame.timestamp()`method to fetch the timestamp of each frame, and use that information to derive a frame rate (if timestamps are constant). See https://docs.rs/webp-animation/0.6.0/webp_animation/struct.Frame.html#method.timestamp

**Comment by mehmetakify** [comment]
Thank you for descriptive explanation.
